name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Lint
        run: ./gradlew lint detekt ktlintCheck spotlessCheck
      - name: Build with Gradle
        run: ./gradlew build -x lint
      - name: Run Tests
        run: ./gradlew test
      - name: Run Coverage Report
        run: ./gradlew koverXmlReport

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
